name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare zip
        run: |
          zip -r HDR.zip HDR/*
          zip -r HDR-Addons.zip HDR-Addons/*

  
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allow_override: true
          gzip: folders
          tag: beta
          name: beta
          body: Current release build of HDR.
          files: >
            HDR.zip
            HDR-Addons.zip
