name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Release:
    if: "contains(github.event.head_commit.message, 'Release:')" # only run actions if commit message contains "Release:"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python format_addons_list.py
  
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allow_override: true
          gzip: folders
          tag: beta
          name: HDR
          body: Current release build of HDR.
          files: >
            *.zip
            HDR-Addons-List.txt
