name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare zip
        run: |
          
          cd HDR-Base
          zip -r ../HDR-Base.zip *
          cd ..

          cd HDR-Addons
          
          for dir in */
          do
            cd $dir
            dir=${dir%*/}
            echo $dir >> ../../HDR-Addons-List.txt
            zip -r ../../$dir.zip *
            cd ..
          done

          cd ..
  
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allow_override: true
          gzip: folders
          tag: beta
          name: HDR
          body: Current release build of HDR.
          files: >
            *.zip
            HDR-Addons-List.txt
